Bubbla
Status: Resolving address of
waws-prod-blu-007.ftp.azurewebsites.windows.net
Status: Connecting to 23.96.40.14:21...
Status: Connection established, waiting for welcome message...
Response: 220 Microsoft FTP Service
Command: USER xephyrofficla\xephyrofficial
Response: 331 Password required
Command: PASS ***************
Response: 530 User cannot log in.
Error: Critical error
Error: Could not connect to server
is xX_MLG_Xx